export default [
  {
    id: 'sub3',
    accessPath: '/main/home',
    icon: 'ic-shouyegailan',
    isMember: 0,
    isShow: 1,
    parentPermissionId: 0,
    permissionCode: '01',
    permissionName: '首页',
    permissionTypeId: 0,
    systemCode: 'hsjs',
    topsize: 0,
    level: 0,
    hasChild: 1,
    isMenuGroup: 1,
    children: [
      {
        id: '2',
        accessPath: '/main/home',
        icon: 'ic-shouyegailan',
        isMember: 0,
        isShow: 1,
        parentPermissionId: 0,
        permissionCode: '01',
        permissionName: 'ITEM 1',
        permissionTypeId: 0,
        systemCode: 'hsjs',
        topsize: 0,
        level: 0,
        isMenuGroup: 1,
        hasChild: 1,
        children: [
          {
            id: 99,
            accessPath: '/main/home',
            icon: 'ic-shouyegailan',
            isMember: 0,
            isShow: 1,
            parentPermissionId: 0,
            permissionCode: '01',
            permissionName: 'OPTION 1',
            permissionTypeId: 0,
            systemCode: 'hsjs',
            topsize: 0,
            level: 0,
            isMenuGroup: 1,
            hasChild: 0,
            children: []
          },
          {
            id: 3,
            accessPath: '/main/home',
            icon: 'ic-shouyegailan',
            isMember: 0,
            isShow: 1,
            parentPermissionId: 0,
            permissionCode: '01',
            permissionName: 'OPTION 2',
            permissionTypeId: 0,
            systemCode: 'hsjs',
            topsize: 0,
            level: 0,
            isMenuGroup: 1,
            hasChild: 0,
            children: []
          }
        ]
      },
      {

        id: 4,
        accessPath: '/main/home',
        icon: 'ic-shouyegailan',
        isMember: 0,
        isShow: 1,
        parentPermissionId: 0,
        permissionCode: '01',
        permissionName: 'ITEM 2',
        permissionTypeId: 0,
        systemCode: 'hsjs',
        topsize: 0,
        level: 0,
        isMenuGroup: 1,
        hasChild: 1,
        children: [
          {
            id: 5,
            accessPath: '/main/home',
            icon: 'ic-shouyegailan',
            isMember: 0,
            isShow: 1,
            parentPermissionId: 0,
            permissionCode: '01',
            permissionName: 'OPTION 4',
            permissionTypeId: 0,
            systemCode: 'hsjs',
            topsize: 0,
            level: 0,
            isMenuGroup: 0,
            hasChild: 0,
            children: []
          }
        ]
      }
    ],
  },
  {
    accessPath: '/main/13',
    icon: 'ic-shouyegailan',
    isMember: 0,
    isShow: 1,
    id: 13,
    parentPermissionId: 0,
    permissionCode: '01',
    permissionName: 'Navigation Two',
    permissionTypeId: 0,
    systemCode: 'hsjs',
    topsize: 0,
    level: 0,
    hasChild: 1,
    isMenuGroup: 1,
    children: [
      {
        accessPath: '/main/2',
        icon: 'ic-shouyegailan',
        isMember: 0,
        isShow: 1,
        id: 20,
        parentPermissionId: 0,
        permissionCode: '01',
        permissionName: 'option 5',
        permissionTypeId: 0,
        systemCode: 'hsjs',
        topsize: 0,
        level: 0,
        hasChild: 0,
        children: []
      },
      {
        accessPath: '/main/2',
        icon: 'ic-shouyegailan',
        isMember: 0,
        isShow: 1,
        id: 21,
        parentPermissionId: 0,
        permissionCode: '01',
        permissionName: 'option 6',
        permissionTypeId: 0,
        systemCode: 'hsjs',
        topsize: 0,
        level: 0,
        hasChild: 0,
        children: []
      },
      {
        accessPath: '/main/2',
        icon: 'ic-shouyegailan',
        isMember: 0,
        isShow: 1,
        id: 17,
        parentPermissionId: 0,
        permissionCode: '01',
        permissionName: 'option 7',
        permissionTypeId: 0,
        systemCode: 'hsjs',
        topsize: 0,
        level: 0,
        hasChild: 0,
        children: []
      },
      {
        accessPath: '/main/2',
        icon: 'ic-shouyegailan',
        isMember: 0,
        isShow: 1,
        id: 18,
        parentPermissionId: 0,
        permissionCode: '01',
        permissionName: 'option 18',
        permissionTypeId: 0,
        systemCode: 'hsjs',
        topsize: 0,
        level: 0,
        hasChild: 0,
        children: []
      },
      {
        accessPath: '/main/2',
        icon: 'ic-shouyegailan',
        isMember: 0,
        isShow: 1,
        id: 19,
        parentPermissionId: 0,
        permissionCode: '01',
        permissionName: 'option 19',
        permissionTypeId: 0,
        systemCode: 'hsjs',
        topsize: 0,
        level: 0,
        hasChild: 0,
        children: []
      }
    ]
  },
  {
    accessPath: '/main/13',
    icon: 'ic-shouyegailan',
    isMember: 0,
    isShow: 1,
    id: 14,
    parentPermissionId: 0,
    permissionCode: '01',
    permissionName: '13',
    permissionTypeId: 0,
    systemCode: 'hsjs',
    topsize: 0,
    level: 0,
    hasChild: 0,
    children: []
  },
  {
    accessPath: '/main/13',
    icon: 'ic-shouyegailan',
    isMember: 0,
    isShow: 1,
    id: 15,
    parentPermissionId: 0,
    permissionCode: '01',
    permissionName: '13',
    permissionTypeId: 0,
    systemCode: 'hsjs',
    topsize: 0,
    level: 0,
    hasChild: 0,
    children: []
  },
  {
    accessPath: '/main/13',
    icon: 'ic-shouyegailan',
    isMember: 0,
    isShow: 1,
    id: 16,
    parentPermissionId: 0,
    permissionCode: '01',
    permissionName: '13',
    permissionTypeId: 0,
    systemCode: 'hsjs',
    topsize: 0,
    level: 0,
    hasChild: 0,
    children: []
  }
]

